POST http://localhost:3001/api/blogs/6007462a675bbd2528bc97bb/comments
Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzbWl0aCIsImlkIjoiNWZjOWE4MjE1ZWI5NWQ2NDZmY2QwZTc5IiwiaWF0IjoxNjA3MTExOTUzfQ.g2tloo6L2dBUMzOpIErd9lTwyTOIYaQSb9dwCqn4zLg

{
  
  "comment": "Test comment 2" 
}

